import { useEffect, useState } from 'react'
import { Search, Download, ExternalLink, Box, LoaderCircle, Check, AlertCircle, Library as LibraryIcon, ArrowLeft, ChevronLeft, ChevronRight, FolderOpen } from 'lucide-react'
import type { Model, SearchResponse, SourceResult, SourceAvailability } from './types'

const sourceOrder=['printables','makerworld']
const niceName:Record<string,string>={printables:'Printables',makerworld:'MakerWorld'}

export default function App(){
  const [query,setQuery]=useState(''); const [response,setResponse]=useState<SearchResponse|null>(null)
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [selected,setSelected]=useState<Model[]>([])
  const [job,setJob]=useState<{status:string;progress:number;message:string;project_path?:string;path?:string;files?:Record<string,{status:string;reason?:string}>}|null>(null)
  const [retrying,setRetrying]=useState<string|null>(null)
  const [availability,setAvailability]=useState<SourceAvailability[]>([]); const [openStatus,setOpenStatus]=useState<string|null>(null)
  const [view,setView]=useState<'search'|'library'>('search')
  useEffect(()=>{fetch('/api/sources/status').then(r=>r.json()).then(data=>setAvailability(data.sources||[])).catch(()=>{})},[])
  async function search(e?:React.FormEvent){e?.preventDefault(); if(!query.trim()||busy)return; setBusy(true);setError('');setSelected([]);setJob(null)
    try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:query.trim()})});if(!r.ok)throw new Error(`Search failed (${r.status})`);setResponse(await r.json());fetch("/api/sources/status").then(result=>result.json()).then(data=>setAvailability(data.sources||[])).catch(()=>{})}catch(e){setError(e instanceof Error?e.message:'Unable to search')}finally{setBusy(false)}}
  function toggle(m:Model){setSelected(old=>old.some(x=>x.source===m.source&&x.id===m.id)?old.filter(x=>!(x.source===m.source&&x.id===m.id)):old.length<5?[...old,m]:old)}
  async function pollJob(initial:{job_id:string}){let done=false
      while(!done){const p=await fetch(`/api/projects/${initial.job_id}`);const state=await p.json();setJob(state);done=['completed','complete','partial','failed'].includes(state.status);if(!done)await new Promise(resolve=>setTimeout(resolve,900))}
  }
  async function download(){if(!response||!selected.length)return;setJob({status:'queued',progress:0,message:'Starting download…'});setError('')
    try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:response.query,models:selected.map(m=>({source:m.source,model_id:m.id,model_url:m.model_url}))})});if(!r.ok)throw new Error((await r.json()).detail||'Could not start project download');await pollJob(await r.json())
    }catch(e){setError(e instanceof Error?e.message:'Download failed')}}
  async function retrySource(source:string){if(!response)return;setRetrying(source)
    try{const r=await fetch('/api/search/source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:response.query,source})});if(!r.ok)throw new Error(`Retry failed (${r.status})`);const updated:SourceResult=await r.json();setResponse(old=>old?{...old,total_results:old.total_results-(old.sources.find(s=>s.source===source)?.results.length||0)+updated.results.length,sources:old.sources.map(s=>s.source===source?updated:s)}:old);fetch("/api/sources/status").then(result=>result.json()).then(data=>setAvailability(data.sources||[])).catch(()=>{})}catch(e){setError(e instanceof Error?e.message:'Source retry failed')}finally{setRetrying(null)}}
  const groups=sourceOrder.map(key=>response?.sources.find(x=>x.source===key)).filter(Boolean) as SourceResult[]
  if(view==='library') return <LibraryPage onBack={()=>setView('search')}/>
  return <main className="shell">
    <header className="top"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('search')}}><span className="brandIcon"><Box size={20}/></span>FORM<span className="brandDim">FINDER</span></a><div className="topActions"><button className="libraryLink" onClick={()=>setView('library')}><LibraryIcon size={15}/>Library</button><span className="local">LOCAL WORKSPACE</span></div></header>
    <section className="hero"><div className="eyebrow">YOUR NEXT PRINT STARTS HERE</div><h1>Find a model.<br/><em>Make it yours.</em></h1><p>Search across the 3D maker community and collect models in one organized project.</p>
      <form className="search" onSubmit={search}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for a model…" aria-label="Search for a model"/><button disabled={busy||!query.trim()}>{busy?<LoaderCircle className="spin" size={17}/>:null}{busy?'Searching':'Search models'}</button></form>
      {error&&<div className="error"><AlertCircle size={16}/>{error}</div>}
    </section>
    <section className="sourcesPanel"><div className="eyebrow">SOURCES</div><div className="sourceAvailability">{sourceOrder.map(key=>{const item=availability.find(source=>source.id===key);const ok=item&&['success','success_empty'].includes(item.status);return <button className="sourcePill" key={key} onClick={()=>setOpenStatus(openStatus===key?null:key)}><span className={ok?'ok':'warn'}>{ok?'✓':'⚠'}</span>{niceName[key]}</button>})}</div>{openStatus&&(()=>{const item=availability.find(source=>source.id===openStatus);return item?<div className="sourceDetails"><b>{item.name}</b><span>Status: {item.status}</span><span>Access method: {item.access_mode} · {item.search_method}</span><span>Last check: {item.last_check||'Not checked yet'}</span>{item.message&&<span>Reason: {item.message}</span>}{item.status==='blocked'&&<span>Try a normal browser login with <code>python -m app.tools.browser_login {item.id}</code>, then enable authenticated access.</span>}</div>:null})()}</section>
    {job&&<div className={`job ${job.status}`}><div className="jobText">{['completed','complete'].includes(job.status)?<Check size={16}/>:['failed','partial'].includes(job.status)?<AlertCircle size={16}/>:<LoaderCircle size={16} className="spin"/>}{job.message}{job.path&&<span> · {job.path}</span>}</div>{job.files&&Object.entries(job.files).length>0&&<div className="fileProgress">{Object.entries(job.files).map(([name,state])=><span key={name}>{state.status==='completed'?'✓':state.status==='failed'?'⚠':'…'} {name}{state.reason?` · ${state.reason}`:''}</span>)}</div>}<div className="progress"><i style={{width:`${job.progress}%`}}/></div></div>}
    {response&&<section className="results"><div className="resultsHead"><div><div className="eyebrow">COMMUNITY RESULTS</div><h2>“{response.query}” <span>{response.total_results} found</span></h2></div><div className="downloadArea"><span className="counter">Selected <b>{selected.length}</b> / 5</span><button className="downloadBtn" onClick={download} disabled={!selected.length||!!job&&['queued','searching','downloading'].includes(job.status)}><Download size={16}/>{job&&['queued','searching','downloading'].includes(job.status)?'Downloading…':`Download selected (${selected.length})`}</button></div></div>
      {groups.map(group=><section className="source" key={group.source}><div className="sourceHead"><h3>{niceName[group.source]||group.label}</h3><div className="sourceActions">{['success','success_empty'].includes(group.status)?<span className="status">{group.status==='success_empty'?'0 RESULTS':`${group.results.length} RESULTS`}</span>:<><span className="status bad">{group.status.replace(/_/g,' ').toUpperCase()}</span><button className="retry" onClick={()=>retrySource(group.source)} disabled={retrying!==null}>{retrying===group.source?<LoaderCircle size={13} className="spin"/>:'Retry'}</button></>}</div></div>
        {group.status==='success_empty'?<div className="sourceMessage">No models found for this search.</div>:!['success'].includes(group.status)?<div className="sourceMessage"><strong>Unable to access {niceName[group.source]||group.label}.</strong><br/>{group.error?.message||'The source is unavailable right now.'}<div className="unavailableActions"><button className="retry" onClick={()=>retrySource(group.source)} disabled={retrying!==null}>{retrying===group.source?'Retrying…':'Retry source'}</button><a href={sourceWebsite(group.source)} target="_blank" rel="noreferrer">Open website ↗</a></div></div>:<div className="grid">{group.results.map(model=><Card key={`${model.source}-${model.id}`} model={model} chosen={selected.some(x=>x.source===model.source&&x.id===model.id)} disabled={!selected.some(x=>x.source===model.source&&x.id===model.id)&&selected.length>=5} onToggle={()=>toggle(model)}/>)}</div>}
      </section>)}
    </section>}
    {!response&&!busy&&<section className="below"><div className="belowIcon"><Search size={22}/></div><span>TWO COMMUNITIES · ONE SEARCH</span><p>Printables and MakerWorld.</p></section>}
    <footer><span>FORMFINDER <i>·</i> PERSONAL MAKER TOOL</span><span>Respect each model’s license and source attribution.</span></footer>
  </main>
}

type LibraryFile={name:string;path:string;category:string;extension:string;size_bytes:number;modified_at:string;url:string}
type LibraryVersion={version:string;title:string;author:string|null;source:string|null;model_id:string|null;model_url:string|null;license:string|null;description:string|null;status:string;downloaded_at:string|null;files:LibraryFile[];file_count:number}
type LibraryProject={id:string;name:string;query:string;created_at:string;updated_at:string;version_count:number;file_count:number;versions:LibraryVersion[]}

function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;if(bytes<1024*1024*1024)return `${(bytes/1024/1024).toFixed(1)} MB`;return `${(bytes/1024/1024/1024).toFixed(1)} GB`}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'':date.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}

function LibraryPage({onBack}:{onBack:()=>void}){
  const [projects,setProjects]=useState<LibraryProject[]>([]); const [selected,setSelected]=useState<LibraryProject|null>(null)
  const [query,setQuery]=useState(''); const [sort,setSort]=useState('updated'); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [busy,setBusy]=useState(true); const [error,setError]=useState('')
  async function load(nextPage=page){setBusy(true);setError('');try{const params=new URLSearchParams({page:String(nextPage),page_size:'20',sort});if(query.trim())params.set('q',query.trim());const response=await fetch(`/api/library?${params}`);if(!response.ok)throw new Error('Could not load the library');const data=await response.json();setProjects(data.projects||[]);setPages(data.pages||1);setTotal(data.total||0);setPage(nextPage)}catch(error){setError(error instanceof Error?error.message:'Could not load the library')}finally{setBusy(false)}}
  useEffect(()=>{load(1)},[sort])
  async function openProject(id:string){setBusy(true);setError('');try{const response=await fetch(`/api/library/${encodeURIComponent(id)}`);if(!response.ok)throw new Error('Could not open this project');setSelected(await response.json())}catch(error){setError(error instanceof Error?error.message:'Could not open this project')}finally{setBusy(false)}}
  if(selected) return <main className="shell libraryShell"><header className="top"><button className="backLink" onClick={()=>setSelected(null)}><ArrowLeft size={15}/> Library</button><span className="local">PROJECT DETAIL</span></header><section className="libraryDetail"><button className="quietButton" onClick={()=>setSelected(null)}><ArrowLeft size={15}/>All projects</button><div className="eyebrow">PROJECT LIBRARY</div><h1>{selected.name.replace(/_/g,' ')}</h1><p className="libraryLead">{selected.query} · {selected.version_count} print{selected.version_count===1?'':'s'} · {selected.file_count} file{selected.file_count===1?'':'s'}</p><div className="versionList">{selected.versions.map(version=><article className="versionCard" key={version.version}><div className="versionTop"><div><span className="versionBadge">{version.version}</span><h2>{version.title}</h2><p>{version.author?`by ${version.author}`:'Creator not listed'}{version.source&&` · ${version.source}`}</p></div><span className={`versionStatus ${version.status}`}>{version.status}</span></div>{version.model_url&&<a className="original" href={version.model_url} target="_blank" rel="noreferrer">View original <ExternalLink size={13}/></a>}<div className="libraryFiles">{version.files.map(file=><a className="libraryFile" href={file.url} target="_blank" rel="noreferrer" key={file.path}><span><b>{file.name}</b><small>{file.category} · {formatBytes(file.size_bytes)}</small></span><ExternalLink size={14}/></a>)}</div></article>)}</div></section></main>
  return <main className="shell libraryShell"><header className="top"><button className="backLink" onClick={onBack}><ArrowLeft size={15}/> Search</button><span className="local">PROJECT LIBRARY</span></header><section className="libraryHero"><div><div className="eyebrow">YOUR WORKSPACE</div><h1>Project library.</h1><p>Every downloaded print, grouped by project and version.</p></div><div className="libraryCount"><FolderOpen size={18}/><b>{total}</b><span>projects</span></div></section><div className="libraryToolbar"><form className="librarySearch" onSubmit={e=>{e.preventDefault();load(1)}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a project…"/><button>Search</button></form><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort projects"><option value="updated">Recently updated</option><option value="name">Name</option><option value="files">Most files</option></select></div>{error&&<div className="error">{error}</div>}{busy?<div className="libraryEmpty"><LoaderCircle className="spin" size={20}/> Loading library…</div>:projects.length===0?<div className="libraryEmpty"><FolderOpen size={25}/><b>No projects found</b><span>Downloaded projects will appear here.</span></div>:<div className="projectGrid">{projects.map(project=>{const firstFile=project.versions.flatMap(version=>version.files).find(file=>file.category==='Image');return <button className="projectCard" key={project.id} onClick={()=>openProject(project.id)}><div className="projectThumb">{firstFile?<img src={firstFile.url} loading="lazy"/>:<FolderOpen size={30}/>}<span>{project.version_count} version{project.version_count===1?'':'s'}</span></div><div className="projectBody"><h2>{project.name.replace(/_/g,' ')}</h2><p>{project.query}</p><small>{project.file_count} file{project.file_count===1?'':'s'} · updated {formatDate(project.updated_at)}</small></div></button>})}</div>}<div className="pagination"><button disabled={page<=1||busy} onClick={()=>load(page-1)}><ChevronLeft size={16}/>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages||busy} onClick={()=>load(page+1)}>Next<ChevronRight size={16}/></button></div><footer><span>FORMFINDER <i>·</i> PERSONAL MAKER TOOL</span><span>Projects stay on this machine.</span></footer></main>
}

function sourceWebsite(source:string){return ({printables:'https://www.printables.com',makerworld:'https://makerworld.com'} as Record<string,string>)[source]||'https://example.com'}

function Card({model,chosen,disabled,onToggle}:{model:Model;chosen:boolean;disabled:boolean;onToggle:()=>void}){
  const popularity=model.downloads!=null?`${model.downloads.toLocaleString()} downloads`:model.likes!=null?`${model.likes.toLocaleString()} likes`:model.favorites!=null?`${model.favorites.toLocaleString()} saves`:null
  const files=[...new Set(model.available_files.map(f=>f.category).filter(x=>x!=='OTHER'))]
  return <article className={`card ${chosen?'chosen':''}`}><div className="thumb">{model.thumbnail_url?<img src={model.thumbnail_url} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<div className="placeholder"><Box size={29}/></div>}<label className={`select ${chosen?'checked':''}`} title={disabled?'Maximum of 5 selected':'Select model'}><input type="checkbox" checked={chosen} disabled={disabled} onChange={onToggle}/>{chosen?<Check size={15}/>:null}</label><span className="sourceTag">{niceName[model.source]}</span></div>
    <div className="cardBody"><h4 title={model.title}>{model.title}</h4><div className="byline">{model.author?<>by <b>{model.author}</b></>:'Creator not listed'}</div><div className="stats">{popularity&&<span>{popularity}</span>}{model.rating!=null&&<span>★ {model.rating.toFixed(1)}</span>}{!popularity&&model.rating==null&&<span>Community model</span>}</div>
      <div className="fileRow">{files.length?files.map(f=><span key={f} className="fileChip">{f}</span>):<span className="muted">Files shown on model page</span>}</div>
      <a className="original" href={model.model_url} target="_blank" rel="noreferrer">View original <ExternalLink size={13}/></a>
    </div></article>
}
